# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install NPM packages
        run: npm install > install.log 2>&1
        
      - name: Prettify!
        run: npx prettier --write . > prettify.log 2>&1
        
      - name: Commit Back
        run: |
          git add .
          git reset .github
          git config user.name "github-actions"
          git commit -m "actions"
          git push
